name: Alistamiento ambiente

on:
    [push]
jobs:
  deployPROD:
    name: Environment&Compile
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load dependencies
        uses: ./.github/actions/setup-composite
          