name: Compilacion ambiente

on: [push]

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

jobs:
  deployPROD:
    name: Environment&Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false # This is required to keep the build files

      - name: Alistando ambiente
        uses:  SETUPJAVA5/.github/workflows/example1.yml
      - name: Revisando Java 5
        run: |
          echo Running new install java 5
          echo Started on `date`
          echo "Print folder"
          echo $JAVA_HOME
          echo $JAVA_HOME
          echo $PATH
          echo "PATH changed"
          echo $PATH
          echo "java version"
          echo Done on `date`

      - name: Revisnando instalacion
        run: | # Install Ant, specifict version that supports Java 5
          echo $PATH
          echo "PATH changed"
          echo $PATH
