name: Compilacion ambiente

on: [push]

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

jobs:
  deployPROD:
    name: Environment&Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false # This is required to keep the build files

      - name: Alistando ambiente
        uses: alex9609/setup-java5-ant1.9/.github/actions/setup-java5@v1.2
        with:
            path-java: 'jdk-1_5_0_12-linux-amd64.bin'

      - name: Alistando ambiente
        uses: alex9609/setup-java5-ant1.9/.github/actions/setup-ant1.9@v1.2
        with:
            path-ant: 'apache-ant-1.7.1-bin.tar.gz'

      - name: Comprobando instalacion
        run: |
         cd /usr/lib/jvm/java5/
         ls -la
         cd /usr/lib/jvm/
         ls -la