name: Compilacion ambiente

on: [push]

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

jobs:
  deployPROD:
    name: Environment&Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false # This is required to keep the build files

      - name: Alistando ambiente
        uses: ./.github/actions
        with:
            path-java: 'jdk-1_5_0_12-linux-amd64.bin'

      - name: Comprobando instalacion
        run: |
         cd /usr/lib/jvm/java5/
         ls -la
         cd /usr/lib/jvm/
         ls -la