name: Compilacion ambiente

on: [push]

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

jobs:
  deployPROD:
    name: Environment&Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false # This is required to keep the build files

      - name: Listando carpetas
        run: |
           ls -la
           cd ${{ github.workspace }}/.github
           ls -la
           cd ./.github

      - name: Alistando ambiente
        uses: ./.github/workflows/actions/setup-composite@master
